config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'code' => 'pages#code'
  get 'login' => 'pages#login'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def code
  end

  def about
  end

  def login
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>pyNoob!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<!--HERE IS WHERE YOU PASTE THE CODE FROM BOOTSTRAP NAVBAR OR LAYOUT DESIGN-->
<body> 
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "[ pyNoobs! ].net",root_path, class: "navbar-brand" %> <!--MAKES BRAND NAME CLICKABLE TO ROOT_PATH-->
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      </ul> <!--This is the navbar buttons-->    
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "[ Home ]", root_path %></li>
        <li><%= link_to "[ About ]", about_path %></li>
        <li><%= link_to "[ Code ]", code_path %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!--HERE IS WHERE YOU PASTE THE CODE FROM BOOTSTRAP NAVBAR OR LAYOUT DESIGN-->

<!--This class container moves the text from STARUP page out of leftside "blank page"-->
	<div class="container">
  		<%= yield %>
	</div>


</body>
</html>

app/views/pages/about.html.erb
<div class = "jumbotron">
<h2>About us</h2> 
<h6>THIS PAGE IS UNDER CONSTRUCTION</h6>
<h6>...</h6>

<pre>
insert code here...
</pre> <!--CODE INSERTION-->

</div>

app/views/pages/code.html.erb
<div class = "jumbotron">
<h2>Code</h2> 
<h6>THIS PAGE IS UNDER CONSTRUCTION</h6>

<pre>
insert code here...
</pre> <!--CODE INSERTION-->

app/views/pages/home.html.erb
<!--THIS IS THE HOME PAGE JUMBOTRON DESIGN FROM BOOTSTRAP,
you can add the "center class" to "Jumbotron class" to center everything inside "Jumbotron"-->
<div class = "jumbotron center">
	<h1>[ pyNoobs! ]</h1>	
	<p>   click  <%= link_to "here", code_path , class: "btn btn-primary" %> to start!</p>
</div>

<div class = "jumbotron center">
	<h6>[ pyNoobs! ].net THIS PAGE IS UNDER CONSTRUCTION</h6>
</div>